#!/bin/bash

# Change the attribute of a directory to trigger the allocating and linking of
# the log page.

# When making a new directory, two dentry will be added into it, the '.' and '..'
# each of them is 56 bytes (48 + 8)
# to make the log full, (4096 - 48 - 48) / 256 ~= 15

# Each new file will added one dentry to it with 256 bytes long

# For NOVA, a log page is 4 KiB, each page has a tail (32 bytes), thus, we need
# (4096 - 56 * 2 - 32) / (256).
# remaining 112 bytes after the creating 15 long name files

# Then, create a file with 60 bytes name can fill it (60 + 48 = 108 ~= 112)

# At last, change the attribute to append a new attr-change log, which will
# trigger the allocating and linking of a new log page.

mkdir /mnt/pmem0/dir
touch /mnt/pmem0/dir/num_01_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_lon
touch /mnt/pmem0/dir/num_02_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_lon
touch /mnt/pmem0/dir/num_03_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_lon
touch /mnt/pmem0/dir/num_04_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_lon
touch /mnt/pmem0/dir/num_05_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_lon
touch /mnt/pmem0/dir/num_06_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_lon
touch /mnt/pmem0/dir/num_07_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_lon
touch /mnt/pmem0/dir/num_08_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_lon
touch /mnt/pmem0/dir/num_09_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_lon
touch /mnt/pmem0/dir/num_10_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_lon
touch /mnt/pmem0/dir/num_11_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_lon
touch /mnt/pmem0/dir/num_12_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_lon
touch /mnt/pmem0/dir/num_13_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_lon
touch /mnt/pmem0/dir/num_14_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_lon
touch /mnt/pmem0/dir/num_15_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_long_name_file_lon
touch /mnt/pmem0/dir/num_16_long_name_file_long_name_file_long_name_file_long_nam

chmod -R 777 /mnt/pmem0/dir
